--
-- VHDL ARCHITECTURE ECE411.REG16.UNTITLED
--
-- CREATED:
--          BY - HERSTAD.STDT (EESN26.EWS.UIUC.EDU)
--          AT - 14:04:22 03/31/03
--
-- GENERATED BY MENTOR GRAPHICS' HDL DESIGNER(TM) 2001.5 (BUILD 170)
--
-- HDS INTERFACE_START
LIBRARY IEEE;
USE IEEE.STD_LOGIC_1164.ALL;
USE IEEE.NUMERIC_STD.ALL;
LIBRARY ECE411;
USE ECE411.LC3B_TYPES.ALL;

ENTITY ControlWordREG IS
   PORT( 
      RESET_L : IN     STD_LOGIC;
      A       : IN     Control_Word;
      EN      : IN     STD_LOGIC;
      CLK     : IN     STD_LOGIC;
      F       : OUT    Control_Word
   );

-- Declarations

END ControlWordREG ;

-- HDS INTERFACE_END
ARCHITECTURE UNTITLED OF ControlWordREG IS
BEGIN
	ControlWordREG: PROCESS(CLK,RESET_L,A,EN)
	VARIABLE STATE : Control_Word;
	BEGIN
		IF(RESET_L = '0') THEN
		  -- ID init
			STATE.id.SelB := '0';
			-- EX init
			STATE.ex.OffSel := "00";
	    STATE.ex.PCOffSel := '0';
	    STATE.ex.ALUSel1 := "00";
	    STATE.ex.ALUSel2 := '0';
	    STATE.ex.ALUop := "000";
      STATE.ex.isSTB := '0';
      STATE.ex.ExNeedsOp := '0';
      STATE.ex.HasOp2 := '0';
	    --MEM init
	    STATE.mem.AddrSel := '0';
	    STATE.mem.mwriteH_L := '1';
      STATE.mem.mwriteL_L := '1';
      STATE.mem.mread_L := '1';
      STATE.mem.isBR := '1';
      STATE.mem.MemNotUsed := '1';
      STATE.mem.OneStepMem := '0';
      STATE.mem.uncondBR := '0';
      STATE.mem.BrAddrSel := '0';
      STATE.mem.MemForwardEn := '0';
      STATE.mem.MemNeedsOp := '0';
      STATE.mem.RequestBaseR := '0';
      STATE.mem.writeBTB := '0';
      STATE.mem.isNOTaNOP := '0';
      --WB init
	    STATE.wb.SetCC := '0';
	    STATE.wb.MemArSel := "00";
      STATE.wb.ld_Reg := '0';
      STATE.wb.DestSel := '0';
      STATE.wb.isLDB := '0';
      STATE.wb.WBForwardEn := '0';
      --NAME init
			STATE.name := name_NOP;
		ELSIF(CLK = '1' AND CLK'EVENT AND EN = '1') THEN -- HIGH ENABLE
			STATE := A;
		ELSIF(EN /= '0' AND EN /= '1' AND CLK = '1' AND CLK'EVENT) THEN
			-- ID init
			STATE.id.SelB := 'X';
			-- EX init
			STATE.ex.OffSel := "XX";
	    STATE.ex.PCOffSel := 'X';
	    STATE.ex.ALUSel1 := "XX";
	    STATE.ex.ALUSel2 := 'X';
	    STATE.ex.ALUop := "XXX";
			STATE.ex.isSTB := 'X';
	    --MEM init
	    STATE.mem.AddrSel := 'X';
	    STATE.mem.mwriteH_L := 'X';
      STATE.mem.mwriteL_L := 'X';
      STATE.mem.mread_L := 'X';
      STATE.mem.isBR := 'X';
      STATE.mem.MemNotUsed := 'X';
      STATE.mem.OneStepMem := 'X';
      STATE.mem.uncondBR := 'X';
      STATE.mem.BrAddrSel := 'X';
      STATE.mem.MemForwardEn := 'X';
      STATE.mem.RequestBaseR := 'X';
      STATE.mem.writeBTB := 'X';
      STATE.mem.isNOTaNOP := 'X';
      --WB init
	    STATE.wb.SetCC := 'X';
	    STATE.wb.MemArSel := "XX";
      STATE.wb.ld_Reg := 'X';
      STATE.wb.DestSel := 'X';
      STATE.wb.isLDB := 'X';
      STATE.wb.WBForwardEn := '0';
      
      --NAME init
			STATE.name := name_rti;
		END IF;
		F <= STATE AFTER DELAY_REG;
	END PROCESS ControlWordREG;
END UNTITLED;
