-- VHDL Entity ece411.grabmwrite.generatedInstance
--
-- Created:
--          by - hinz1.ews (gelib-057-33.ews.illinois.edu)
--          at - 16:14:05 04/12/13
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2012.1 (Build 6)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.NUMERIC_STD.all;

LIBRARY ece411;
USE ece411.LC3b_types.all;

ENTITY grabmwrite IS
   PORT( 
      CtrlWord : IN     Control_Word;
      mwrite0  : OUT    STD_LOGIC
   );

END grabmwrite ;

-- 
-- Auto generated dummy architecture for leaf level instance.
-- 
ARCHITECTURE generatedInstance OF grabmwrite IS 
BEGIN


END generatedInstance;
